INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_RUNNING_AGREGATE_FUNC running_agregate_func)

FIND_PATH(
    RUNNING_AGREGATE_FUNC_INCLUDE_DIRS
    NAMES running_agregate_func/api.h
    HINTS $ENV{RUNNING_AGREGATE_FUNC_DIR}/include
        ${PC_RUNNING_AGREGATE_FUNC_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    RUNNING_AGREGATE_FUNC_LIBRARIES
    NAMES gnuradio-running_agregate_func
    HINTS $ENV{RUNNING_AGREGATE_FUNC_DIR}/lib
        ${PC_RUNNING_AGREGATE_FUNC_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(RUNNING_AGREGATE_FUNC DEFAULT_MSG RUNNING_AGREGATE_FUNC_LIBRARIES RUNNING_AGREGATE_FUNC_INCLUDE_DIRS)
MARK_AS_ADVANCED(RUNNING_AGREGATE_FUNC_LIBRARIES RUNNING_AGREGATE_FUNC_INCLUDE_DIRS)

